linters:
  enable:
    - revive
    - unconvert
    - dupl
    - goconst
    - gofmt
    - misspell
    - unparam
    - nakedret
    - prealloc
    - gosec
linters-settings:
  misspell:
    locale: US
  revive:
    rules:
      - name: unused-parameter
        exclude:
          - "TEST"
          - "**/credential.go"
          - "**/audit_logger.go"
issues:
  max-same: 0
  max-per-linter: 0
  exclude-use-default: false
  exclude:
    # gosec: Duplicated errcheck checks
    - G104
  exclude-files:
    - ".*example.*\\.go"
